services:
  postgresdb:
    image: postgres
    environment:
      - POSTGRES_USER=coursefinder
      - POSTGRES_PASSWORD=coursefinder
      - POSTGRES_DB=coursefinderDB

  purdue-course-finder:
    build: .
    image: purdue-course-finder:latest
    ports:
      - "8443:8443"
    depends_on:
      - postgresdb